# Generated by Django 2.1.2 on 2018-11-13 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startFundraiser', '0002_auto_20181106_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('cc', 'campaign created'), ('cd', 'campaign started'), ('ces', 'campaign ended successfully'), ('ceu', 'campaign ended unsuccessfully')], default='Campaign Created', max_length=5)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='startFundraiser.Campaign')),
            ],
            options={
                'verbose_name_plural': 'Campaign Status',
            },
        ),
    ]
