# Generated by Django 2.1.2 on 2018-11-16 18:25

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('startFundraiser', '0003_campaignstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startFundraiser.Campaign')),
            ],
        ),
        migrations.AlterField(
            model_name='campaignstatus',
            name='status',
            field=models.CharField(choices=[('cc', 'campaign created'), ('cd', 'campaign started'), ('ces', 'campaign ended successfully'), ('ceu', 'campaign ended unsuccessfully')], default='cc', max_length=5),
        ),
    ]
